"Driver_ver1.0"
66yurimi99/DriverMonitoring_AutoDriving pull request #3
Opened 2023-10-22 09:22 UTC by jis0202

prototype1.0 driver complete

2023-10-23 20:50 UTC, 66yurimi99 requested changes
👍 고생하셨습니당

추가로, 이후 모듈화를 할 때 참고하면 좋은 내용이 있어 함께 첨부드립니다.
[[Design Pattern][C++] 인터페이스와 커플링](https://0xd00d00.github.io/2021/08/06/design_pattern_5.html)

2023-10-23 20:50 UTC, 66yurimi99 commented on Codes/Driver/ISP.cpp
> +    // ������ ���� ��ǥ ����
`ISP.h`, `ISP.cpp` 파일에서 한글 깨짐 현상이 생기는 것 같아요.
인코딩 설정 확인 부탁드립니다!

2023-10-24 05:10 UTC, jis0202 commented on Codes/Driver/ISP.cpp
> +    // ������ ���� ��ǥ ����
다 고쳤습니다!

2023-10-24 05:16 UTC, jis0202 commented
Diver_ver1.0 수정 완료했습니다 @66yurimi99

2023-10-24 05:20 UTC, 66yurimi99 approved these changes
고생하셨습니당 🥇 🥇 
@akaError404 @jis0202

2023-10-24 05:20 UTC, merged